---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adoptium-project

resources:
- namespace.yaml

components:
- ../../../../components/project-admin-rolebindings/adoptium
