presubmits:
  - name: kustomize-build
    decorate: true
    max_concurrency: 1
    skip_if_only_changed: "^docs/|\\.md$|^(OWNERS|LICENSE)$|^\\."
    skip_report: false
    context: aicoe-ci/prow/kustomize-build
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:latest
          command:
            - "test-kustomize-build"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "1"

  - name: kubeval-validation
    decorate: true
    max_concurrency: 1
    skip_if_only_changed: "^docs/|\\.md$|^(OWNERS|LICENSE)$|^\\."
    skip_report: false
    context: aicoe-ci/prow/kubeval-validation
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:latest
          command:
            - "test-kubeval-validation"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1"

  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "500Mi"
              cpu: "300m"
            limits:
              memory: "1Gi"
              cpu: "300m"

  - name: tekton-hello-world
    decorate: true
    skip_report: false
    max_concurrency: 10
    path_alias: https://github.com/Gregory-Pereira/aicoe-ci/tree/opf-hello-world-pipeline
    agent: tekton-pipeline
    run_if_changed: "^\\.test\\.yml"
    labels:
      preset-dind-enabled: "true"
      preset-quay-credentials: "true"
    pipeline_run_spec:
        pipelineRef:
          name: opf-tekton-hello-world
        resources:
        - name: testing
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
    trigger: "(?m)^/build opf-hello-world,?(\\s+|$)"
    rerun_command: "/rebuild opf-hello-world"
