---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: thanos-receive
  namespace: opf-observatorium
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  to:
    kind: Service
    name: thanos-receive-oauth-proxy
  port:
    targetPort: oauth-proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
