apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kepler
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'kepler-edge'
      server: 'https://api.odh-cl1.apps.os-climate.org:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:kepler:project-admin, applications, *, kepler/kepler-osc, allow
        - p, proj:kepler:project-admin, applications, *, kepler/kepler-edge-osc, allow
      groups:
        - kepler-admins
  namespaceResourceWhitelist:
    - group: ""
      kind: Node
