---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-grafana-public
resources:
  - ../smaug/dashboards
  - ../smaug/datasources
  - ../../../base

patchesStrategicMerge:
  - ./grafana-public.yaml
  - ./grafana-route-public.yaml
  - ./servicemonitor.yaml
