apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gohan-cluster-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: gohan-cluster-secret
  dataFrom:
    - extract:
        key: moc/infra/argocd/gohan-cluster-secret
