---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../common
  - ../../../../base/cert-manager.io/issuers/ingress-letsencrypt-production
  - ../../../../base/config.openshift.io/oauths/cluster
  - ../../../../base/core/namespaces/acme-operator
  - ../../../../base/operators.coreos.com/subscriptions/cert-manager
  - ../../../../base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator
  - ../../../../base/rbac.authorization.k8s.io/clusterroles/acme-operator
  - ../../../../base/user.openshift.io/groups/cluster-admins
  - certificates/default-ingress-certificate.yaml
  - ingresscontrollers/default.yaml

generators:
  - secret-generator.yaml

patchesStrategicMerge:
  - oauths/cluster_patch.yaml
  - groups/cluster-admins.enc.yaml
