---
apiVersion: v1
kind: Service
metadata:
  name: loki-query-frontend-oauth-proxy
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: loki-query-frontend-tls
spec:
  selector:
    app: loki-query-frontend-oauth-proxy
  ports:
    - name: oauth-proxy
      port: 9091
      protocol: TCP
      targetPort: oauth-proxy
