apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: backup-vault
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  workspaces:
    - name: snapshots
      mountPath: /snapshots
    - name: backup-job
      mountPath: /backup-job
    - name: utility-scripts
      mountPath: /utility-scripts
  steps:
    - name: create-snapshot
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/create-snapshot.sh'
        - $(workspaces.snapshots.path)
        - $(context.taskRun.namespace)
    - name: backup-snapshot-to-s3
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      workingDir: /workspace
      command:
        - '/utility-scripts/backup-snapshot-to-s3.sh'
        - $(workspaces.snapshots.path)
    - name: cleanup-old-taskruns
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/cleanup-old-taskruns.sh'
