---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: triage-party
  name: triage-party-pcache
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: triage-party
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
  volumeMode: Filesystem
