---
apiVersion: apps/v1
kind: PersistentVolume
metadata:
  name: pcache
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: 172.17.0.2
    path: /app/pcache
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
