kind: ConfigMap
apiVersion: v1
metadata:
    annotations:
        kustomize.config.k8s.io/behavior: merge
    name: cluster-monitoring-config
    namespace: openshift-monitoring
data:
    config.yaml: |
        enableUserWorkload: true
        prometheusK8s:
          externalLabels:
            cluster: moc/smaug
