apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- externalsecrets/loki-thanos-object-storage.yaml
- externalsecrets/openshift-logging-lokistack-gateway-bearer-token.yaml
