apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/operators.coreos.com/subscriptions/cert-manager
- ../../../../base/user.openshift.io/groups/cluster-admins
- ../../../../bundles/external-secrets-operator
- ../common
- apiserver
- configmaps/service-catalog-k8s-plugin.yaml
- ingresscontrollers
- secret-mgmt
- ../../../../base/core/persistentvolumeclaims/image-registry-storage
- ../../../../base/imageregistry.operator.openshift.io/configs/cluster
patchesStrategicMerge:
- groups/cluster-admins.yaml
