---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-observatorium
commonLabels:
  app.kubernetes.io/part-of: observatorium
  app.kubernetes.io/name: thanos
resources:
  - deployments
  - horizontalpodautoscalers
  - rolebindings
  - roles
  - routes
  - serviceaccounts
  - servicemonitors
  - services
patchesStrategicMerge:
  - deployments/observatorium-thanos-query.yaml
