kind: Secret
apiVersion: v1
metadata:
    name: s3buckets
    namespace: odh-trino
stringData:
    OPERATE_FIRST_GENERAL_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:fsnv7jo7f+0+KhSfN2T7epPrj7Q=,iv:R/cBrbrV+YpMIsEfnbDUAnoGlV/edDFCdhYF8nH/i8w=,tag:EOz9+LZductVSlE/58qxBQ==,type:str]
    OPERATE_FIRST_GENERAL_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OCfkm6S92lo4wUZTtSWZJTE7yseMJ9rnI7NbZBEx8LmMjS2bqIBXgg==,iv:RBSNWAnpIremO4V1VlpnGyrbIqw2e+IYZLi53K0FuMQ=,tag:NNTlnpHDmoUh5LfjQbqW/A==,type:str]
    OPERATE_FIRST_GENERAL_BUCKET: ENC[AES256_GCM,data:giN0BlEA6WYHSIbB+nWc,iv:ehhXVUQQWcGE13cAXiP+I1+Zy+AJl0y8WiLvGYRilP0=,tag:Pbf0HecjxPgDYuQaArGYng==,type:str]
    OPERATE_FIRST_GENERAL_REGION: ""
    OPERATE_FIRST_GENERAL_S3_ENDPOINT: ENC[AES256_GCM,data:UshJNc/sTcPJ4Cb9Sml3a4zVd/x85wRHNm6eavZYAXCZ8JyT4D9q8gchvESsks/9klbKmzLR,iv:6G93Ljh1a72+IQVvQ7KnKVih1a7Ae3I3ETHJXdMf7Js=,tag:UEskbcmPSfCxloSKX48upA==,type:str]
    OPERATE_FIRST_GENERAL_S3_ENDPOINT_URL_PREFIX: ENC[AES256_GCM,data:tAgstGDWBOk=,iv:YuALOTuZoKpdnadPj4egGvC3UoBLji+OoMdQNkVYtLI=,tag:iOuQCKKb36yDB1bPipgUqw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-09-01T17:37:29Z"
    mac: ENC[AES256_GCM,data:nC4xzGqmq4g3jI95h60q4wFEJwF76NTPpwbI6Ul18EGTmj7QZ/BI8M1W9MjRdtcBuEnhcMCm1kiqWRrldsoqy+f9BgO38CGCj6NNxH56h/cBMz5DK6U7rqyvNG7gmLPPCFsfcLQ820qyEr6FNuV+eWQD6jAwZ/lSRnU3R0WybnQ=,iv:Al6MwsQK4uUv+rzw9Dpx1vAVteWjb74HJDf/iPmRBcA=,tag:XCJGAiEcgiwS2xZ/3ibOHw==,type:str]
    pgp:
        - created_at: "2022-09-01T17:37:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA9aKBcudqifiARAASVJGCDX/3i+jANpESD05wjBmZvli6sDGjfHG7RyLnYID
            YocF3+onGsngl63+0Y0O4TNwmhYomkYA9wO60w365A2mqCJlj/ZOn37LGvku6WRh
            lmH4CYSQcmjdLYNTwtPLRNtHSZDEDVGKuZk1a/+yGWalDVFVE7D6X/dFfBEK56Vk
            kOEwRmV6L/2scfIf3s2S9wUf6U5XTla5g88sWTCAuey/SbJuftQ1UYGpDpttmhTw
            g4U5zg5m3WpfrJyPauV7nwmorMfnBGudk65kXYGx37I9PyKTds++M8/F4JaHoJEV
            Qj5+hiG1u2vGSC869WukDHMWeb2p7SnTJDc3IZ08igFH9aAkfhsCLhF17qcjh90C
            lQhWsxv/WYDA4xkRW8QpWmzM0Qqjj1qmigO9giikbMIoNi3DeAn12m3+vgdUOuNx
            Qqt/7BhxpJdz6jEf4xa6Q+pA0UwnjyVNJdU1mEezhNNW8J8gFIJJRsDX8yMWyIKi
            ZkD95H/Sc70LPzRlsBxhjYOAOc58lchHMbAlmPleI+oxi5ErNN229D80DUCuwcrp
            5zHnlZub5k/8E9ghiqXN/7AJOLXBGT8Zkgz4L9aMSfU8sJSVMXYaPVLEYyDx8XYw
            uyrGE8YXfla/t4GGVvr2tq0NbDnJqkOJzzKvRPwIr9rnupHMQBnD7NL3HUF+P2DS
            5gH6IfB23PN33vfMDVw1t+BeUWT+TWRQsCqnYIWq0QxuEleB8opEwy2s//tzabv+
            CiWzwzimUwJPArxHAkvqofjkCbutyW8XQ2Obus9ebzWGd+Ka6lbPAA==
            =DTUu
            -----END PGP MESSAGE-----
          fp: 0508677DD04952D06A943D5B4DC4116D360E3276
    encrypted_regex: stringData
    version: 3.7.1
