apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
nameSuffix: -smaug
resources:
- apex
- apicurio
- b4mad
- cluster-management
- data-science
- janus-idp
- okd-team
- operate-first
- thoth
- octo-otel-dev
- copilot-ops
- kruize
