---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: trino-catalog
    files:
      - jmx.properties
      - catalogs/osc_datacommons_dev.properties
      - catalogs/osc_datacommons_hive_ingest.properties
      - catalogs/kafka_fx.properties
      - catalogs/riskthinking.properties
  - name: trino-configfiles
    files:
      - config-coordinator.properties
      - config-worker.properties
      - jvm-coordinator.config
      - jvm-worker.config
      - log.properties
      - node.properties
      - password-authenticator.properties
      - password.db
      - group-provider.properties
      - group-mapping.properties
      - access-control.properties
      - rules.json
  - name: kafka-table-description-dir
    files:
      - kafka-table-description-dir/fx.json
      - kafka-table-description-dir/kepler.json
      - kafka-table-description-dir/ecb-trino-schema.json
