apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: multiclusterhub-operator-pull-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: multiclusterhub-operator-pull-secret
  dataFrom:
    - extract:
        key: moc/infra/open-cluster-management-observability/multiclusterhub-operator-pull-secret
