apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lokistack-gateway-bearer-token
  namespace: openshift-logging
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: lokistack-gateway-bearer-token
  dataFrom:
    - extract:
        key: emea/jerry/openshift-logging/lokistack-gateway-bearer-token
