kind: Deployment
apiVersion: apps/v1
metadata:
  name: observatorium-thanos-query-frontend
  namespace: opf-observatorium
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: opf-observatorium-smaug
    app.kubernetes.io/name: thanos
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2021-11-11-aee7c97b
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: query-frontend
      app.kubernetes.io/instance: opf-observatorium-smaug
      app.kubernetes.io/name: thanos
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: main-2021-11-11-aee7c97b
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query-frontend
        app.kubernetes.io/instance: opf-observatorium-smaug
        app.kubernetes.io/name: thanos
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: main-2021-11-11-aee7c97b
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          terminationMessagePath: /dev/termination-log
          name: thanos-query-frontend
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
          env:
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/thanos/thanos:main-2021-11-11-aee7c97b'
          args:
            - query-frontend
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--query-frontend.compress-responses'
            - '--http-address=0.0.0.0:9090'
            - '--query-frontend.downstream-url=http://observatorium-thanos-query.$(NAMESPACE).svc.cluster.local.:9090'
            - '--query-frontend.log-queries-longer-than=5s'
            - '--query-range.response-cache-config="config":
                "max_size": "0"
                "max_size_items": 2048
                "validity": "6h"
              "type": "in-memory"'
            - '--query-range.split-interval=24h'
            - '--labels.split-interval=24h'
            - '--query-range.max-retries-per-request=0'
            - '--labels.max-retries-per-request=0'
            - '--labels.default-time-range=336h'
            - '--labels.response-cache-config="config":
                "max_size": "0"
                "max_size_items": 2048
                "validity": "6h"
              "type": "in-memory"'
            - '--cache-compression-type=snappy'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
