kind: Deployment
apiVersion: apps/v1
metadata:
  name: observatorium-thanos-query
  namespace: opf-observatorium
  labels:
    app.kubernetes.io/component: query
    app.kubernetes.io/instance: opf-observatorium-smaug
    app.kubernetes.io/name: thanos
    app.kubernetes.io/part-of: observatorium
    app.kubernetes.io/version: main-2021-11-11-aee7c97b
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: query
      app.kubernetes.io/instance: opf-observatorium-smaug
      app.kubernetes.io/name: thanos
      app.kubernetes.io/part-of: observatorium
      app.kubernetes.io/version: main-2021-11-11-aee7c97b
  template:
    metadata:
      labels:
        app.kubernetes.io/component: query
        app.kubernetes.io/instance: opf-observatorium-smaug
        app.kubernetes.io/name: thanos
        app.kubernetes.io/part-of: observatorium
        app.kubernetes.io/version: main-2021-11-11-aee7c97b
    spec:
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 20
          terminationMessagePath: /dev/termination-log
          name: thanos-query
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
          env:
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
          ports:
            - name: grpc
              containerPort: 10901
              protocol: TCP
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: https
              containerPort: 9091
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: FallbackToLogsOnError
          image: 'quay.io/thanos/thanos:main-2021-11-11-aee7c97b'
          args:
            - query
            - '--grpc-address=0.0.0.0:10901'
            - '--http-address=0.0.0.0:9090'
            - '--log.level=info'
            - '--log.format=logfmt'
            - '--query.replica-label=replica'
            - '--query.replica-label=rule_replica'
            - '--query.replica-label=prometheus_replica'
            - '--store=dnssrv+_grpc._tcp.observatorium-thanos-rule.opf-observatorium.svc.cluster.local'
            - '--store=dnssrv+_grpc._tcp.observatorium-thanos-store-shard-0.opf-observatorium.svc.cluster.local'
            - '--store=dnssrv+_grpc._tcp.observatorium-thanos-store-shard-1.opf-observatorium.svc.cluster.local'
            - '--store=dnssrv+_grpc._tcp.observatorium-thanos-store-shard-2.opf-observatorium.svc.cluster.local'
            - '--store=dnssrv+_grpc._tcp.observatorium-thanos-receive-default.opf-observatorium.svc.cluster.local'
            - '--web.prefix-header=X-Forwarded-Prefix'
            - '--query.timeout=15m'
            - '--query.lookback-delta=15m'
            - '--query.auto-downsampling'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
