---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: loki-frontend
spec:
  to:
    kind: Service
    name: loki-query-frontend-oauth-proxy
  port:
    targetPort: oauth-proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
